name: Run tests

on: [push, pull_request]

jobs:
  run_tests:
    strategy:
      matrix:
        include:
          - nvim_tag: v0.5.0
            ts_commit: 4542402e34568eb607059e3ff6a3594aaca850fd
          - nvim_tag: v0.5.1
            ts_commit: 4542402e34568eb607059e3ff6a3594aaca850fd
          - nvim_tag: v0.6.0
            ts_commit: 4542402e34568eb607059e3ff6a3594aaca850fd
          - nvim_tag: v0.6.1
            ts_commit: 4542402e34568eb607059e3ff6a3594aaca850fd
          - nvim_tag: v0.7.0
            ts_commit: master

    name: Run tests
    runs-on: ubuntu-latest
    env:
      NVIM_TAG: ${{ matrix.nvim_tag }}
      TS_COMMIT: ${{ matrix.ts_commit }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh

      - name: Install tree-sitter CLI
        run: |
          npm install -g tree-sitter-cli

      - name: Ensure TS parsers installed
        run: |
          nvim --headless -c "TSInstallSync all" -c "q"

      - name: Run tests
        run: |
          bash ./run_tests.sh
